fieldLayouts:
  e73b4186-2fad-4c0f-8eae-bbb884932c58:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 6a0c610e-4e47-4716-a63d-8728b4de0d91
            warning: null
            width: 100
        name: Content
        uid: 9e1ec516-06db-4ea2-bcbb-7dfafe62a1a5
fs: site
handle: site
name: Site
sortOrder: 0
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
